// LV522 source visual content adapted to working TGMC parents.
// Generated by tools/restart_colony_ports.py; no passive compatibility type stubs.

/turf/closed/wall/shiva
	parent_type = /turf/closed/wall
	name = "prefabricated structure wall"
	desc = "This structure is made of metal support rods and robust poly-kevlon plastics. A derivative of the stuff used in UA ballistics vests, USCM and UPP uniforms. These walls are pulled taught and have been reinforced into a more permanent structure."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_shiva_lv522.dmi'
	icon_state = "turf_closed_wall_shiva_lv522-0"
	base_icon_state = "turf_closed_wall_shiva_lv522"
	smoothing_flags = SMOOTH_BITMASK

/turf/closed/wall/r_wall/shiva
	parent_type = /turf/closed/wall/r_wall
	name = "reinforced prefabricated structure wall"
	desc = "This structure is made of metal support rods. The poly-kevlon has been replaced with sheet metal, reinforcing it."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_r_wall_shiva_lv522.dmi'
	icon_state = "turf_closed_wall_r_wall_shiva_lv522-0"
	base_icon_state = "turf_closed_wall_r_wall_shiva_lv522"
	smoothing_flags = SMOOTH_BITMASK

/turf/closed/wall/r_wall/shiva/hull
	parent_type = /turf/closed/wall/r_wall
	name = "reinforced prefabricated structure wall"
	desc = "It cannot be destroyed by any means you have available. Perhaps praying to the gods may help."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_r_wall_shiva_hull_lv522.dmi'
	icon_state = "turf_closed_wall_r_wall_shiva_hull_lv522-0"
	base_icon_state = "turf_closed_wall_r_wall_shiva_hull_lv522"
	smoothing_flags = SMOOTH_BITMASK
	resistance_flags = RESIST_ALL

/turf/closed/mineral/smooth/strata_ice
	parent_type = /turf/closed/mineral/smooth
	name = "ice columns"
	desc = "Columns and crags stacked atop one another. They defiantly push towards the heavens, but are stopped short by dripping frigid excess."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_mineral_smooth_strata_ice_lv522.dmi'
	icon_state = "turf_closed_mineral_smooth_strata_ice_lv522-0"
	base_icon_state = "turf_closed_mineral_smooth_strata_ice_lv522"
	smoothing_flags = SMOOTH_BITMASK
	resistance_flags = RESIST_ALL

/turf/closed/wall/strata_outpost
	parent_type = /turf/closed/wall
	name = "bare outpost walls"
	desc = "A thick and chunky metal wall. The surface is barren and imposing."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_strata_outpost_lv522.dmi'
	icon_state = "turf_closed_wall_strata_outpost_lv522-0"
	base_icon_state = "turf_closed_wall_strata_outpost_lv522"
	smoothing_flags = SMOOTH_BITMASK

/turf/closed/wall/r_wall/strata_outpost
	parent_type = /turf/closed/wall/r_wall
	name = "ribbed outpost walls"
	desc = "A thick and chunky metal wall covered in jagged ribs."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_r_wall_strata_outpost_lv522.dmi'
	icon_state = "turf_closed_wall_r_wall_strata_outpost_lv522-0"
	base_icon_state = "turf_closed_wall_r_wall_strata_outpost_lv522"
	smoothing_flags = SMOOTH_BITMASK

/turf/closed/wall/r_wall/strata_outpost/hull
	parent_type = /turf/closed/wall/r_wall
	name = "ribbed outpost walls"
	desc = "A thick and chunky metal wall that is, just by virtue of its placement and imposing presence, entirely indestructible."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_r_wall_strata_outpost_hull_lv522.dmi'
	icon_state = "turf_closed_wall_r_wall_strata_outpost_hull_lv522-0"
	base_icon_state = "turf_closed_wall_r_wall_strata_outpost_hull_lv522"
	smoothing_flags = SMOOTH_BITMASK
	resistance_flags = RESIST_ALL

/turf/closed/wall/strata_outpost/ribbed
	parent_type = /turf/closed/wall
	name = "ribbed outpost walls"
	desc = "A thick and chunky metal wall covered in jagged ribs."
	icon = 'temp/LV522/icons/turf/walls/turf_closed_wall_strata_outpost_ribbed_lv522.dmi'
	icon_state = "turf_closed_wall_strata_outpost_ribbed_lv522-0"
	base_icon_state = "turf_closed_wall_strata_outpost_ribbed_lv522"
	smoothing_flags = SMOOTH_BITMASK

/obj/structure/prop/lv522/obj_effect_spider_spiderling_nogrow
	parent_type = /obj/structure/prop
	anchored = FALSE
	density = FALSE
	desc = "It never stays still for long."
	icon = 'temp/LV522/icons/effects/effects.dmi'
	icon_state = "spiderling"
	name = "spiderling"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_l42a_ap
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_l42"
	name = "magazine box (AP L42A x 16)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_l42a_ext
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_l42"
	name = "magazine box (Ext L42A x 12)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_m4ra_ap_empty
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_m4ra"
	name = "magazine box (AP M4RA x 16)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_misc_flares
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A box of M94 marking flare packs, to brighten up your day."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "supply_crate"
	name = "\improper box of M94 marking flare packs"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_misc_mre
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A box of MREs. Nutritious, but not delicious."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "supply_crate"
	name = "\improper box of MREs"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_misc_mre_empty
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A box of MREs. Nutritious, but not delicious."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "supply_crate"
	name = "\improper box of MREs"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_nailgun_empty
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_nailgun"
	name = "magazine box (Nailgun x 10)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_shotgun
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_slug"
	name = "\improper shotgun shell box (Slugs x 100)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_shotgun_beanbag_empty
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_bean"
	name = "\improper shotgun shell box (Beanbag x 100)"

/obj/structure/prop/lv522/obj_item_ammo_box_magazine_shotgun_buckshot_empty
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_buck"
	name = "\improper shotgun shell box (Buckshot x 100)"

/obj/structure/prop/lv522/obj_item_ammo_box_rounds_empty
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A 10x24mm ammunition box. Used to refill M41A MK1, MK2, M4RA and M41AE2 HPR magazines. It comes with a leather strap allowing to wear it on the back."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_m41"
	name = "\improper rifle ammunition box (10x24mm)"

/obj/structure/prop/lv522/obj_item_ammo_box_rounds_smg
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A 10x20mm ammunition box. Used to refill M39 HV and extended magazines. It comes with a leather strap allowing to wear it on the back."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi'
	icon_state = "base_m39"
	name = "\improper SMG HV ammunition box (10x20mm)"

/obj/structure/prop/lv522/obj_item_co2_cartridge
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A cartridge of compressed CO2 for the M8 cartridge bayonet. Do not consume or puncture."
	icon = 'temp/LV522/icons/obj/items/tank.dmi'
	icon_state = "co2_cartridge"
	name = "\improper CO2 cartridge"

/obj/structure/prop/lv522/obj_item_cpr_dummy
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "A CPR dummy, for training all those privates how to save a life! Does not accurately emulate battle wounds, does not simulate rib breaking, plastic toxic to touch, please contact a doctor if skin irritation persists for more than two hours."
	icon = 'temp/LV522/icons/obj/items/cpr_dummy.dmi'
	icon_state = "cpr_dummy"
	name = "\improper CPR dummy"

/obj/structure/prop/lv522/obj_item_defenses_handheld_sentry
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A compact version of the USCM defenses. Designed for quick deployment of the associated type in the field."
	icon = 'temp/LV522/icons/obj/structures/machinery/defenses/sentry.dmi'
	icon_state = "Normal uac_sentry_handheld"
	name = "handheld UA 571-C sentry gun"

/obj/structure/prop/lv522/obj_item_defenses_handheld_sentry_mini
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A compact version of the USCM defenses. Designed for quick deployment of the associated type in the field."
	icon = 'temp/LV522/icons/obj/structures/machinery/defenses/sentry.dmi'
	icon_state = "Mini uac_sentry_handheld"
	name = "handheld UA 512-M mini sentry"

/obj/structure/prop/lv522/obj_item_device_analyzer_plant_analyzer
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A hand-held environmental scanner which reports current gas levels."
	icon = 'temp/LV522/icons/obj/items/devices.dmi'
	icon_state = "hydro"
	name = "plant analyzer"

/obj/structure/prop/lv522/obj_item_device_cassette_tape_indie
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A plastic cassette tape with the Japanese Rising Sun."
	icon = 'temp/LV522/icons/obj/items/walkman.dmi'
	icon_state = "cassette_rising_sun"
	name = "rising sun cassette"

/obj/structure/prop/lv522/obj_item_device_cassette_tape_nam
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A green plastic cassette tape."
	icon = 'temp/LV522/icons/obj/items/walkman.dmi'
	icon_state = "cassette_green"
	name = "green cassette"

/obj/structure/prop/lv522/obj_item_device_cassette_tape_pop1
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A plastic cassette tape with a blue sticker."
	icon = 'temp/LV522/icons/obj/items/walkman.dmi'
	icon_state = "cassette_blue"
	name = "blue cassette"

/obj/structure/prop/lv522/obj_item_device_cassette_tape_pop4
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A plastic cassette tape with a pink striped sticker."
	icon = 'temp/LV522/icons/obj/items/walkman.dmi'
	icon_state = "cassette_pink_stripe"
	name = "pink cassette"

/obj/structure/prop/lv522/obj_item_device_m56d_gun
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "The top half of a M56D heavy machine gun post. However it ain't much use without the tripod."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/guns_by_faction/USCM/machineguns.dmi'
	name = "\improper M56D heavy machine gun"
	pixel_x = -8

/obj/structure/prop/lv522/obj_item_device_m56d_post
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "The folded, foldable tripod mount for the M56D. (Place on ground and drag to you to unfold)."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/guns_by_faction/USCM/hmg.dmi'
	icon_state = "folded_mount"
	name = "\improper M56D folded mount"

/obj/structure/prop/lv522/obj_item_device_sentry_computer
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A laptop loaded with sentry control software."
	icon = 'temp/LV522/icons/obj/structures/props/sentrycomp.dmi'
	icon_state = "sentrycomp_cl"
	name = "\improper Sentry Gun Network Laptop"

/obj/structure/prop/lv522/obj_item_device_walkman
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A Synsound cassette player that first hit the market over 200 years ago. Crazy how these never went out of style."
	icon = 'temp/LV522/icons/obj/items/walkman.dmi'
	icon_state = "walkman_1"
	name = "Synsound Walkman"

/obj/structure/prop/lv522/obj_item_falcon_drone
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "An agile drone used by Yautja to survey the hunting grounds."
	icon = 'temp/LV522/icons/obj/items/hunter/pred_gear.dmi'
	icon_state = "falcon_drone"
	name = "falcon drone"

/obj/structure/prop/lv522/obj_item_hardpoint_locomotion_van_wheels
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "Integral to the movement of the van."
	icon = 'temp/LV522/icons/obj/vehicles/hardpoints/van.dmi'
	icon_state = "tires"
	name = "vehicle wheels"

/obj/structure/prop/lv522/obj_item_m_gift
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "One, standard issue USCM Present."
	icon = 'temp/LV522/icons/obj/items/gifts.dmi'
	icon_state = "gift1"
	name = "Present"

/obj/structure/prop/lv522/obj_item_maintenance_jack
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A combination crowbar, wrench, and generally large bludgeoning device that comes in handy in emergencies. Can be used to disengage door jacks. Pretty hefty, though."
	icon = 'temp/LV522/icons/obj/items/tools.dmi'
	icon_state = "maintenance_jack"
	name = "\improper K92 Maintenance Jack"

/obj/structure/prop/lv522/obj_item_paper_bin
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/paper.dmi'
	icon_state = "paper_bin1"
	name = "paper bin"

/obj/structure/prop/lv522/obj_item_paper_bin_uscm
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/paper.dmi'
	icon_state = "paper_bin1"
	name = "paper bin"

/obj/structure/prop/lv522/obj_item_paper_bin_wy
	parent_type = /obj/structure/prop
	density = FALSE
	icon = 'temp/LV522/icons/obj/items/paper.dmi'
	icon_state = "paper_bin1"
	name = "paper bin"

/obj/structure/prop/lv522/obj_item_prop_alien_hugger
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "It has some sort of a tube at the end of its tail. What the hell is this thing?"
	icon = 'temp/LV522/icons/mob/xenos/effects.dmi'
	icon_state = "facehugger_impregnated"
	name = "????"

/obj/structure/prop/lv522/obj_item_prop_almayer_flight_recorder
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A small red box that contains flight data from a dropship while it's on mission. Usually referred to as the black box, although this one comes in bloody red."
	icon = 'temp/LV522/icons/obj/structures/props/almayer/almayer_props.dmi'
	icon_state = "flight_recorder"
	name = "\improper FR-112 flight recorder"

/obj/structure/prop/lv522/obj_item_prop_almayer_flight_recorder_colony
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A small red box that records colony announcements, colonist flatlines and other key readouts. Usually referred to the black box, although this one comes in bloody red."
	icon = 'temp/LV522/icons/obj/structures/props/almayer/almayer_props.dmi'
	icon_state = "flight_recorder"
	name = "\improper CIR-60 colony information recorder"

/obj/structure/prop/lv522/obj_item_prop_colony_canister
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A jerry can. In space! Or maybe a colony."
	icon = 'temp/LV522/icons/obj/items/tank.dmi'
	icon_state = "canister"
	name = "fuel can"

/obj/structure/prop/lv522/obj_item_prop_colony_game
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A ThinkPad Systems Game-Bro Handheld (TSGBH, shortened). It can play chess, checkers, tri-d chess, and it also runs Byond! Except this one is out of batteries."
	icon = 'temp/LV522/icons/obj/items/toy.dmi'
	icon_state = "game_kit"
	name = "portable game kit"

/obj/structure/prop/lv522/obj_item_prop_colony_proptag
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A fallen marine's information dog tag. It reads,(BLANK)"
	icon = 'temp/LV522/icons/obj/items/card.dmi'
	icon_state = "dogtag_taken"
	name = "information dog tag"

/obj/structure/prop/lv522/obj_item_prop_colony_used_flare
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "A used USCM issued flare. There are instructions on the side, it reads 'pull cord, make light'."
	icon = 'temp/LV522/icons/obj/items/lighting.dmi'
	icon_state = "flare-empty"
	name = "flare"

/obj/structure/prop/lv522/obj_item_prop_colony_usedbandage
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "Some used gauze."
	icon = 'temp/LV522/icons/obj/structures/props/furniture/misc.dmi'
	icon_state = "bandages_prop"
	name = "dirty bandages"

/obj/structure/prop/lv522/obj_item_prop_helmetgarb_lucky_feather
	parent_type = /obj/structure/prop
	color = "red"
	density = FALSE
	desc = "It is a riotous red color, made of really crummy plastic and synthetic threading, you know, the same sort of material every Corporate Liaison's spine is made of."
	icon = 'temp/LV522/icons/obj/items/clothing/helmet_garb.dmi'
	icon_state = "lucky_feather"
	name = "\improper Red Lucky Feather"

/obj/structure/prop/lv522/obj_item_prop_helmetgarb_spacejam_tickets
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "Two original, crisp, orange, tickets to the one and only Space Jam of 2181. And what a jam it was."
	icon = 'temp/LV522/icons/obj/items/clothing/helmet_garb.dmi'
	icon_state = "tickets_to_space_jam"
	name = "\improper Tickets to Space Jam"

/obj/structure/prop/lv522/obj_item_weapon_ice_axe_red
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "For climbing, mostly. Makes for a good improvised weapon."
	icon = 'temp/LV522/icons/obj/items/weapons/melee/axes.dmi'
	icon_state = "ice_axe_red"
	name = "ice axe"

/obj/structure/prop/lv522/obj_item_weapon_pole_fancy_cane
	parent_type = /obj/structure/prop
	density = FALSE
	desc = "An ebony cane with a fancy, seemingly-golden tip."
	icon = 'temp/LV522/icons/obj/items/weapons/melee/canes.dmi'
	icon_state = "fancy_cane"
	name = "fancy cane"

/obj/structure/prop/lv522/obj_item_xeno_egg_alpha
	parent_type = /obj/structure/prop
	color = "#ff4040"
	density = FALSE
	desc = "Some sort of egg."
	icon = 'temp/LV522/icons/mob/xenos/effects.dmi'
	icon_state = "egg_item"
	name = "egg"

/obj/structure/prop/lv522/obj_structure_blocker_forcefield_vehicles
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	icon = 'temp/LV522/icons/landmarks.dmi'
	icon_state = "map_blocker"
	name = "forcefield"

/obj/structure/prop/lv522/obj_structure_blocker_invisible_wall
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "You cannot go this way."
	icon = 'temp/LV522/icons/landmarks.dmi'
	name = "invisible wall"
	opacity = FALSE

/obj/structure/prop/lv522/obj_structure_desertdam_decals_road_edge
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	icon = 'temp/LV522/icons/turf/floors/desertdam_map.dmi'
	icon_state = "road_edge_decal1"
	layer = ABOVE_NORMAL_TURF_LAYER
	name = "road"

/obj/structure/prop/lv522/obj_structure_foamed_metal
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A lightweight foamed metal wall."
	icon = 'temp/LV522/icons/effects/effects.dmi'
	icon_state = "metalfoam"
	name = "foamed metal"
	opacity = TRUE

/obj/structure/prop/lv522/obj_structure_holohoop
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "Boom, Shakalaka!"
	icon = 'temp/LV522/icons/obj/structures/props/furniture/misc.dmi'
	icon_state = "hoop"
	name = "basketball hoop"

/obj/structure/prop/lv522/obj_structure_machinery
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	icon = 'temp/LV522/icons/obj/structures/props/stationobjs.dmi'
	layer = OBJ_LAYER
	name = "machinery"

/obj/structure/prop/lv522/obj_structure_machinery_autolathe
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "It produces items using metal and glass."
	icon = 'temp/LV522/icons/obj/structures/machinery/autolathe.dmi'
	icon_state = "autolathe"
	layer = OBJ_LAYER
	name = "\improper autolathe"

/obj/structure/prop/lv522/obj_structure_machinery_blackbox_recorder
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	icon = 'temp/LV522/icons/obj/structures/props/server_equipment.dmi'
	icon_state = "blackbox"
	layer = OBJ_LAYER
	name = "Blackbox Recorder"

/obj/structure/prop/lv522/obj_structure_machinery_body_scanconsole
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	icon = 'temp/LV522/icons/obj/structures/machinery/cryogenics.dmi'
	icon_state = "body_scannerconsole"
	layer = OBJ_LAYER
	name = "body scanner console"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_boozeomat
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A technological marvel, supposedly able to mix just the mixture you'd like to drink the moment you ask for one."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "boozeomat"
	layer = BELOW_OBJ_LAYER
	name = "\improper Booze-O-Mat"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_medical_blood
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "The MarineMed brand blood dispensary is the premier, top-of-the-line blood dispenser of 2105! Get yours today!"
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "blood"
	layer = BELOW_OBJ_LAYER
	name = "\improper MM Blood Dispenser"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_medical_no_access
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "Medical pharmaceutical dispenser. Provided by Wey-Yu Pharmaceuticals Division(TM)."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "med"
	layer = BELOW_OBJ_LAYER
	name = "\improper Wey-Med Plus"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_medical_wall_med_limited
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "A wall-mounted medical equipment dispenser. This version is more limited than standard USCM NanoMeds."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "wallmed"
	layer = BELOW_OBJ_LAYER
	name = "\improper NanoMed"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_tech_comp_storage
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A large storage machine containing various components."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "engi"
	layer = BELOW_OBJ_LAYER
	name = "\improper Component Storage Machine"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_tech_comtech_tools
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A vending machine that stores various extra tools that are useful on the field."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "tool"
	layer = BELOW_OBJ_LAYER
	name = "\improper ColMarTech Squad ComTech Tools Vendor"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_tech_electronics_storage
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "Spare tool vendor. What? Did you expect some witty description?"
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "engivend"
	layer = BELOW_OBJ_LAYER
	name = "\improper Electronics Vendor"

/obj/structure/prop/lv522/obj_structure_machinery_cm_vending_sorted_tech_tool_storage
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A large storage machine containing various tools and devices for general repair."
	icon = 'temp/LV522/icons/obj/structures/machinery/vending.dmi'
	icon_state = "tool"
	layer = BELOW_OBJ_LAYER
	name = "\improper Tool Storage Machine"

/obj/structure/prop/lv522/obj_structure_machinery_colony_floodlight
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	icon = 'temp/LV522/icons/obj/structures/machinery/big_floodlight.dmi'
	icon_state = "flood_s_off"
	name = "colony floodlight"

/obj/structure/prop/lv522/obj_structure_machinery_cryo_cell
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "A donation from the old A.W. project, using cryogenic technology. It slowly heals whoever is inside the tube."
	icon = 'temp/LV522/icons/obj/structures/machinery/cryogenics2.dmi'
	layer = BELOW_OBJ_LAYER
	name = "cryo cell"

/obj/structure/prop/lv522/obj_structure_machinery_defenses_sentry_premade_dumb
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A deployable, semi-automated turret with AI targeting capabilities. Armed with an M30 Autocannon and a high-capacity drum magazine. This one's IFF system has been disabled, and it will open fire on any targets within range."
	icon = 'temp/LV522/icons/obj/structures/machinery/defenses/sentry.dmi'
	icon_state = "premade"
	layer = ABOVE_MOB_LAYER
	name = "modified UA-577 Gauss Turret"

/obj/structure/prop/lv522/obj_structure_machinery_juicer
	parent_type = /obj/structure/prop
	anchored = FALSE
	density = FALSE
	icon = 'temp/LV522/icons/obj/structures/machinery/kitchen.dmi'
	name = "Juicer"

/obj/structure/prop/lv522/obj_structure_machinery_m56d_hmg
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A deployable, heavy machine gun. While it is capable of taking the same rounds as the M56, it fires specialized tungsten rounds for increased armor penetration.<br>Drag its sprite onto yourself to man it. Ctrl-click it to cycle through firemodes."
	icon = 'temp/LV522/icons/obj/items/weapons/guns/guns_by_map/desert/hmg.dmi'
	icon_state = "M56D"
	layer = ABOVE_MOB_LAYER
	name = "\improper M56D heavy machine gun"

/obj/structure/prop/lv522/obj_structure_machinery_medical_pod_bodyscanner
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	icon = 'temp/LV522/icons/obj/structures/machinery/cryogenics.dmi'
	icon_state = "body_scanner"
	layer = OBJ_LAYER
	name = "body scanner"

/obj/structure/prop/lv522/obj_structure_machinery_medical_pod_sleeper
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A fancy bed with built-in injectors, a dialysis machine, and a limited health scanner."
	icon = 'temp/LV522/icons/obj/structures/machinery/cryogenics.dmi'
	icon_state = "sleeper"
	layer = OBJ_LAYER
	name = "sleeper"

/obj/structure/prop/lv522/obj_structure_machinery_mill
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "It is a machine that grinds produce."
	icon = 'temp/LV522/icons/obj/structures/machinery/autolathe.dmi'
	icon_state = "autolathe"
	layer = OBJ_LAYER
	name = "\improper Mill"

/obj/structure/prop/lv522/obj_structure_machinery_sensortower
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "A tower with a lot of delicate sensors made to track weather conditions. This one has been adjusted to track biosignatures. This one is heavily damaged. Use a blowtorch, wirecutters, then a wrench to repair it."
	icon = 'temp/LV522/icons/obj/structures/machinery/motion_sensor_v2.dmi'
	icon_state = "sensor_broken"
	layer = OBJ_LAYER
	name = "\improper experimental sensor tower"

/obj/structure/prop/lv522/obj_structure_machinery_sleep_console
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	icon = 'temp/LV522/icons/obj/structures/machinery/cryogenics.dmi'
	icon_state = "sleeperconsole"
	layer = OBJ_LAYER
	name = "sleeper console"

/obj/structure/prop/lv522/obj_structure_machinery_squeezer
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "It is a machine that squeezes extracts from produce."
	icon = 'temp/LV522/icons/obj/structures/machinery/autolathe.dmi'
	icon_state = "autolathe"
	layer = OBJ_LAYER
	name = "\improper Squeezer"

/obj/structure/prop/lv522/obj_structure_medical_supply_link_green
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "A complex network of pipes and machinery, linking to large storage systems below the deck. Medical vendors linked to this port will be able to infinitely restock supplies."
	icon = 'temp/LV522/icons/effects/warning_stripes.dmi'
	icon_state = "medlink_green_unclamped"
	name = "medilink supply port"

/obj/structure/prop/lv522/obj_structure_target
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "A shooting target. Installed on a holographic display mount to help assess the damage done. While being a close replica of real threats a marine would encounter, it's not a real target - special firing procedures seen in weapons such as XM88 or Holotarget ammo won't have any effect."
	icon = 'temp/LV522/icons/obj/structures/props/target_dummies.dmi'
	name = "shooting target"

/obj/structure/prop/lv522/obj_structure_tent_big
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "Can be torn down with an entrenching tool."
	icon = 'temp/LV522/icons/obj/structures/tents_deployed_classic.dmi'
	icon_state = "big_interior"
	name = "tent"
	opacity = FALSE

/obj/structure/prop/lv522/obj_structure_terminal
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "It's an underfloor wiring terminal for power equipment."
	icon = 'temp/LV522/icons/obj/structures/machinery/power.dmi'
	icon_state = "term"
	name = "terminal"

/obj/structure/prop/lv522/obj_structure_transmitter_colony_net
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "It is a wall mounted telephone. The fine text reads: To log your details with the mainframe please insert your keycard into the slot below. Unfortunately the slot is jammed. You can still use the phone, however."
	icon = 'temp/LV522/icons/obj/structures/phone.dmi'
	icon_state = "wall_phone"
	name = "telephone receiver"

/obj/structure/prop/lv522/obj_structure_transmitter_colony_net_rotary
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = FALSE
	desc = "The finger plate is a little stiff."
	icon = 'temp/LV522/icons/obj/structures/phone.dmi'
	icon_state = "rotary_phone"
	name = "rotary telephone"

/obj/structure/prop/lv522/obj_vehicle_powerloader
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "The Caterpillar P-5000 Work Loader is a commercial mechanized exoskeleton used for lifting heavy materials and objects, first released on January 29, 2025 by Weyland Corporation. An old but trusted design used in warehouses, constructions and military ships everywhere."
	icon = 'temp/LV522/icons/obj/vehicles/powerloader.dmi'
	icon_state = "powerloader_open"
	name = "\improper Caterpillar P-5000 Work Loader"
	pixel_x = -16
	pixel_y = -2

/obj/structure/prop/lv522/obj_vehicle_powerloader_jd
	parent_type = /obj/structure/prop
	anchored = TRUE
	density = TRUE
	desc = "The John Deere 4300 Power Loader is a commercial mechanized exoskeleton used for lifting heavy materials and objects based on the Caterpillar P-5000, first released on January 29, 2025 by the Weyland Corporation. An old but trusted design used in warehouses, constructions and military ships everywhere. This one has a signature green and yellow livery."
	icon = 'temp/LV522/icons/obj/vehicles/powerloader.dmi'
	icon_state = "powerloader_open_jd"
	name = "\improper John Deere 4300 Power Loader"
	pixel_x = -16
	pixel_y = -2

/turf/open/floor/lv522/turf_open_asphalt_cement
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement5"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement1"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement12
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement12"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement14
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement14"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement15
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement15"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement2"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement3"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement4
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement4"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_asphalt_cement_cement9
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/asphalt.dmi'
	icon_state = "cement9"
	name = "concrete"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_auto_turf_sand_layer1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/auto_sand.dmi'
	icon_state = "sand_1"
	name = "auto-sand"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_auto_turf_sand_white_layer0
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/auto_sand.dmi'
	icon_state = "varadero_0"
	name = "auto-sand"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_auto_turf_shale_layer1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/auto_shale.dmi'
	icon_state = "shale_1"
	name = "auto-sand"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_auto_turf_shale_layer2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/auto_shale.dmi'
	icon_state = "shale_2"
	name = "auto-sand"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_almayer_w_y0
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "w-y0"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_almayer_w_y1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "w-y1"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_almayer_w_y2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "w-y2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_bluegrid
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "bcircuit"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_northeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_southeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_brown_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "brown"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_browncorner
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "browncorner"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_browncorner_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "browncorner"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_browncorner_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "browncorner"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_browncorner_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "browncorner"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_marked
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "marked"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_plate
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "plate"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_corsat_squares
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/corsat.dmi'
	icon_state = "squares"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_plating_platingdmg1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "platingdmg1"
	name = "plating"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_plating_platingdmg3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "platingdmg3"
	name = "plating"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_plating_platingdmg3_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "platingdmg3"
	name = "plating"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_platingdmg1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "platingdmg1"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_platingdmg3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "platingdmg3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_northeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_southeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_plate
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue_plate"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_blue_plate_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "blue_plate"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_bluefull
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "bluefull"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_cell_stripe
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "cell_stripe"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_cell_stripe_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "cell_stripe"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_cell_stripe_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "cell_stripe"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_cell_stripe_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "cell_stripe"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkbrownfull2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkbrownfull2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_northeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_southeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurple2_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurple2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkpurplefull2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkpurplefull2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkredfull2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkredfull2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_darkyellowfull2_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "darkyellowfull2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_floor_marked
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "floor_marked"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_floor_marked_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "floor_marked"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_floor_plate
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "floor_plate"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_greenfull
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "greenfull"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_greenfull_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "greenfull"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_greenfull_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "greenfull"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_prison_whitegreenfull
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/prison.dmi'
	icon_state = "whitegreenfull"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_shiva_radiator_tile2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/ice_colony/shiva_floor.dmi'
	icon_state = "radiator_tile2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_blue1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "blue1"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_cyan2_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "cyan2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_floor3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "floor3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan1
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan1"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan1_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan1"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan2_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan2"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_northeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_southeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan3_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan4
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan4"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan4_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan4"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan4_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan4"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_strata_white_cyan4_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/strata_floor.dmi'
	icon_state = "white_cyan4"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken2
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken2"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken3
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken3"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken4
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken4"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken5
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken5"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken6
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken6"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_floor_wood_wood_broken7
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "wood-broken7"
	name = "wooden floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_gm_river
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/ground_map.dmi'
	icon_state = "seashallow"
	name = "river"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_organic_grass
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/floors/floors.dmi'
	icon_state = "grass1"
	name = "grass"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_bottom_left
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin4"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_bottom_right
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin8"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_single_wide_left_to_right
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "floor8"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_single_wide_up_to_down
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin3"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_top_left
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin6"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_light_grey_top_right
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin7"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_can_surgery_medium_grey_single_wide_up_to_down
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin15"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_shuttle_dropship_medium_grey_single_wide_up_to_down
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/shuttle.dmi'
	icon_state = "rasputin15"
	name = "floor"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_east
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_north
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_northeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_northwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_southeast
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_southwest
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE

/turf/open/floor/lv522/turf_open_slippery_hull_dir_west
	parent_type = /turf/open/floor
	icon = 'temp/LV522/icons/turf/almayer.dmi'
	icon_state = "outerhull_dir"
	name = "sloped roof"
	smoothing_flags = NONE
